version: '3'
services:
  db:
    container_name: db
    image: postgres:12
    healthcheck:
      test: ["CMD-SHELL", "pg_isready --username local --dbname ssapi"]
      interval: 5s
      timeout: 5s
      retries: 5
    environment:
      - POSTGRES_USER=local
      - POSTGRES_PASSWORD=local
      - POSTGRES_DB=ssapi
    ports:
      - "5432:5432"
  app:
    build: .
    command: bash -c "python manage.py makemigrations && python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
    container_name: app
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    environment:
      ALLOWED_HOSTS: '["localhost", "127.0.0.1", "0.0.0.0", "your-app-name-name.fly.dev"]'
      CORS_ALLOWED_ORIGINS: '["http://localhost:3000"]'
      DEBUG: "true"
      DATABASE_URL: "postgres://local:local@db:5432/ssapi"
      ENVIRONMENT: "DEV"
      SECRET_KEY: "django-insecure-tx0(q!lqq4qja4z#)608n=%n5yuu!qs8)6rzvza@kx@kilw9gi"
    depends_on:
      db:
        condition: service_healthy
